FROM ros:humble

# 必要パッケージをインストール
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-catkin-pkg \
    python3-pip \
    build-essential \
    git \
    ros-humble-rmw-cyclonedds-cpp \
    libpcl-dev \
    pcl-tools \
 && rm -rf /var/lib/apt/lists/*

# ワークスペース作成
WORKDIR /ros2_ws
RUN mkdir -p src

RUN apt-get update && apt-get install -y libeigen3-dev

ENV CPLUS_INCLUDE_PATH=/usr/include/pcl-1.12:$CPLUS_INCLUDE_PATH
ENV CPLUS_INCLUDE_PATH=/usr/include/eigen3:$CPLUS_INCLUDE_PATH

# pcd2pgm をクローン
RUN git clone https://github.com/LihanChen2004/pcd2pgm src/pcd2pgm

# pcl_conversions を追加
WORKDIR /ros2_ws/src
RUN git clone -b humble https://github.com/ros-perception/pcl_conversions.git

WORKDIR /ros2_ws

# 依存関係を解決
RUN rosdep update && \
    rosdep install -r --from-paths src --ignore-src -y --rosdistro humble \
    --skip-keys="ament_cmake_clang_format pcl_ros"


# # 依存関係を解決
# RUN rosdep update && \
#     rosdep install -r --from-paths src --ignore-src -y --rosdistro humble \
#     --skip-keys="ament_cmake_clang_format pcl_ros pcl_conversions"
    
# ビルド
RUN . /opt/ros/humble/setup.sh && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# 環境をセットアップ
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc && \
    echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc
