FROM ros:humble

# 基本依存
RUN apt-get update && apt-get install -y \
    build-essential cmake git \
    libeigen3-dev libyaml-cpp-dev libpcl-dev \
    libtbb-dev libboost-all-dev \
    libopencv-dev python3-opencv \
    ros-humble-pcl-ros ros-humble-pcl-conversions \
 && rm -rf /var/lib/apt/lists/*

# ===== GTSAM (ソースからビルド) =====
WORKDIR /tmp
RUN git clone https://github.com/borglab/gtsam.git -b 4.2.0 && \
    cd gtsam && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF && \
    make -j$(nproc) && make install && \
    ldconfig && \
    cd / && rm -rf /tmp/gtsam
# ==================================

# ワークスペース
WORKDIR /lidar_ws/src

RUN git clone --recursive https://github.com/koide3/ndt_omp.git
RUN git clone --recursive https://github.com/SMRT-AIST/fast_gicp.git
RUN git clone --recursive -b humble --recursive https://github.com/koide3/hdl_global_localization.git
RUN git clone --recursive -b humble https://github.com/AkamisakaAtsuki/hdl_localization.git
RUN git clone https://github.com/omerssid/pcd_publisher.git

WORKDIR /lidar_ws
RUN . /opt/ros/humble/setup.sh && \
    colcon build --symlink-install --cmake-args "-DCMAKE_BUILD_TYPE=Release"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-rmw-cyclonedds-cpp && \
    rm -rf /var/lib/apt/lists/*

# 既定を CycloneDDS に
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

ENV ROS_DISTRO=humble
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]