<?xml version="1.0"?>
<package format="3">
  <name>qr_tracker</name>
  <version>0.1.0</version>
  <description>Track a QR code and adjust robot position via cmd_vel.</description>

  <maintainer email="apurv.saha@tron.tokyo">Apurv</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>


  <!-- OpenCV is brought via system python3-opencv or pip; not a ROS dep -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
